workflows:
  android-build:
    name: Kivy Android Build
    environment:
      sdk: "30"
      ndk: "21.4.7075529"
      python: "3.9"
    scripts:
      - name: Bağımlılıkları kur
        script: |
          pip install kivy requests plyer pyjnius
      - name: Buildozer ile APK oluştur
        script: |
          pip install buildozer
          buildozer init
          buildozer -v android debug
    artifacts:
      - build/**/outputs/**/*.apk