workflows:
  android-build:
    name: Kivy Android Build
    max_build_duration: 120   # uzun sürebilir, süreyi artırdık
    environment:
      vars:
        PYTHON_VERSION: "3.10"
    scripts:
      - name: Gerekli bağımlılıkları kur
        script: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk \
            unzip \
            zip \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libjpeg-dev \
            libpng-dev \
            libfreetype6-dev \
            git \
            make \
            automake \
            libtool \
            pkg-config \
            python3-dev

          pip install --upgrade pip setuptools wheel
          pip install cython
          pip install kivy requests plyer pyjnius buildozer
      - name: APK oluştur
        script: |
          buildozer -v android debug
    artifacts:
      - bin/*.apk
