workflows:
  android-build:
    name: Kivy Android Build
    max_build_duration: 60
    environment:
      vars:
        PYTHON_VERSION: "3.9"
      groups:
        - default
      xcode: latest
      node: latest
    scripts:
      - name: Bağımlılıkları kur
        script: |
          pip3 install --upgrade pip
          pip3 install kivy requests plyer pyjnius buildozer
      - name: Buildozer ile APK oluştur
        script: |
          buildozer init || true
          buildozer -v android debug
    artifacts:
      - build/**/*.apk
