workflows:
  android-build:
    name: Kivy Android Build
    max_build_duration: 120
    environment:
      vars:
        PYTHON_VERSION: "3.10"
        ANDROID_HOME: "$HOME/android-sdk"
        PATH: "$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/30.0.3:$PATH"
    scripts:
      - name: Sistem bağımlılıklarını kur
        script: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk unzip zip git make automake libtool pkg-config python3-dev \
            libffi-dev libssl-dev libsqlite3-dev zlib1g-dev libjpeg-dev libpng-dev libfreetype6-dev curl wget
          pip install --upgrade pip setuptools wheel cython
          pip install kivy requests plyer pyjnius buildozer

      - name: Android SDK ve Build-tools kur
        script: |
          mkdir -p $ANDROID_HOME
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdtools.zip
          unzip -o cmdtools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-30" "build-tools;30.0.3" "platform-tools" "ndk;21.4.7075529"
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/21.4.7075529
          ls -l $ANDROID_HOME/ndk/21.4.7075529

      - name: APK oluştur
        script: |
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/21.4.7075529
          buildozer -v android debug

    artifacts:
      - bin/*.apk
