workflows:
  android-build:
    name: Kivy Android Build
    max_build_duration: 60
    environment:
      vars:
        PYTHON_VERSION: "3.10"   # Buildozer için uyumlu Python sürümü
    scripts:
      - name: Bağımlılıkları kur
        script: |
          pip install --upgrade pip setuptools wheel
          pip install kivy requests plyer pyjnius buildozer
      - name: APK oluştur
        script: |
          buildozer -v android debug
    artifacts:
      - bin/*.apk
